# Generated by Django 6.0.4 on 2026-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('maintenance', 'Maintenance Informatique'), ('cctv', 'Vidéosurveillance (CCTV)'), ('reseaux', 'Réseaux Wi-Fi & Câblé'), ('alarmes', "Alarmes & Contrôle d'accès"), ('cloud_ia', 'Cloud & Intelligence Artificielle'), ('formation', 'Formation & Certification'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('budget', models.CharField(choices=[('lt100', '< 100 000 FCFA'), ('100_500', '100 000 – 500 000 FCFA'), ('500_1m', '500 000 – 2 000 000 FCFA'), ('gt2m', '+ 2 000 000 FCFA'), ('nd', 'Non défini')], default='nd', max_length=20)),
                ('delai', models.CharField(choices=[('urgent', 'Urgent (Moins de 1 mois)'), ('1_3m', '1 à 3 mois'), ('3_6m', '3 à 6 mois'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de Devis',
                'verbose_name_plural': 'Demandes de Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('sujet', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=150)),
                ('entreprise', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('texte', models.TextField()),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('est_publie', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
