# Generated by Django 4.2.13 on 2026-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='repondu_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
