# Generated by Django 6.0.4 on 2026-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('categorie', models.CharField(choices=[('cctv', 'CCTV & Sécurité'), ('reseaux', 'Réseaux'), ('maintenance', 'Maintenance'), ('cloud', 'Cloud'), ('alarmes', 'Alarmes'), ('formation', 'Formation')], default='cctv', max_length=50)),
                ('client', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Projet Portfolio',
                'ordering': ['ordre', '-date_realisation'],
            },
        ),
    ]
