# Generated by Django 6.0.4 on 2026-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('reponse', models.TextField()),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('services', 'Services'), ('devis', 'Devis & Tarifs')], default='general', max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['categorie', 'ordre'],
            },
        ),
    ]
