# Generated by Django 6.0.4 on 2026-04-19 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('couleur', models.CharField(default='#E87722', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('auteur', models.CharField(default='Équipe NST', max_length=100)),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('extrait', models.TextField(max_length=400)),
                ('contenu', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=300)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_une', models.BooleanField(default=False, verbose_name='Article à la Une')),
                ('temps_lecture', models.IntegerField(default=5, help_text='En minutes')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-date_publication'],
            },
        ),
    ]
