# Generated by Django 6.0.4 on 2026-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='wrench', max_length=50)),
                ('description_courte', models.CharField(max_length=300)),
                ('description_longue', models.TextField()),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('features', models.TextField(blank=True, help_text='Une feature par ligne')),
                ('avantages', models.TextField(blank=True, help_text='Un avantage par ligne')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('ordre', models.IntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['ordre'],
            },
        ),
    ]
